<% if ENV['DATABASE_TYPE'] == 'mysql' %>
common: &common
  adapter: mysql2
  encoding: utf8mb4
  host: 127.0.0.1
  password:
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  username: root
<% elsif ENV['DATABASE_TYPE'] == 'sqlite' %>
common: &common
  adapter: sqlite3
  timeout: 30000
<% elsif ENV['DATABASE_TYPE'] == 'sqlserver' %>
common: &common
  adapter: sqlserver
  host: 127.0.0.1
  password: Passw@rd
  port: <%= ENV['DATABASE_PORT'] || 1433 %>
  timeout: 30000
  username: sa
<% else %>
common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: warning
  password: postgres
  pool: 10
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  timeout: 5000
  username: postgres
<% end %>

development:
  <<: *common
  database: motor_admin_dev

test:
  <<: *common
  database: motor_admin_test

production:
  adapter: postgresql
  pool: 10
  url: <%= ENV['DATABASE_URL'] %>
